2d-linear-pool:
  n_workers: 128
  chunksize: 1_000
  seed: 42
  num_samples: 100_000
  dimension: 2
  output_path: data/state_sde/expressions-pool/

  expression:
    class_path: wienerfm.data_generation.odeformer.FunctionEnvironment
    use_queue: true
    collate_queue_size: 2000
    use_sympy: true
    expand: false
    simplify: false
    use_abs: false
    operators_to_use: "id:1,add:2"
    operators_to_not_repeat: ""
    max_unary_depth: 3
    required_operators: ""
    extra_unary_operators: ""
    extra_binary_operators: ""
    extra_constants: null
    min_dimension: 2
    max_dimension: 2
    max_masked_variables: 0
    enforce_dim: false
    use_controller: true
    train_noise_gamma: 0.0
    eval_noise_gamma: 0.0
    float_precision: 3
    float_descriptor_length: 3
    max_exponent: 100
    max_trajectory_value: 1e2
    discard_stationary_trajectory_prob: 0.9
    max_prefactor: 2
    max_token_len: 0
    tokens_per_batch: 10000
    pad_to_max_dim: true
    use_two_hot: false
    max_int: 10
    min_binary_ops_per_dim: 2
    max_binary_ops_per_dim: 4
    min_unary_ops_per_dim: 4
    max_unary_ops_per_dim: 4
    min_op_prob: 0.01
    max_points: 200
    min_points: 50
    prob_const: 0.0
    prob_prefactor: 1.0
    reduce_num_constants: true
    use_skeleton: false
    prob_rand: 0.0
    time_range: 10.0
    prob_t: 0.0
    train_subsample_ratio: 0.5
    eval_subsample_ratio: 0.0
    solve_ode: false
    ode_integrator: "solve_ivp"
    init_scale: 1.0
    fixed_init_scale: false
    c_min: 0.001
    c_max: 1.0
    sample_type: normal