dataset_name: state_sde_nonlinear

n_workers: 2
chunksize: 100
batch_size: 500

train:
  seed: 42
  num_samples: 1_000
  n_paths: 100
  output_path: C:/Users/cesar/Desktop/Projects/FoundationalModelsForStochastics/fimodemix/data/expressions-pool-small/dimension_1/

  sde:
    dimension: 1
    hyper_grid:
      name: Regular
      lower_bound: 1
      upper_bound: 10
      grid_size: 640
      grid_size_eval: 128

    initial_condition:
      distribution: Normal
      parameters:
        mean: [0]
        std: [1]

    drift_pool: C:/Users/cesar/Desktop/Projects/FoundationalModelsForStochastics/fimodemix/data/expressions-pool-small/dimension_1/1d-nonlinear-pool-filtered.csv
    diffusion_pool: C:/Users/cesar/Desktop/Projects/FoundationalModelsForStochastics/fimodemix/data/expressions-pool-small/dimension_1/1d-nonlinear-pool-filtered.csv
