dataset_name: state_sde

n_workers: 5
chunksize: 100
batch_size: 500

train:
  seed: 42
  num_samples: 10_000
  n_paths: 100
  output_path: data/state_sde_full/expressions_3d/dimension_1/

  sde:
    dimension: 3
    hyper_grid:
      name: Regular
      lower_bound: 1
      upper_bound: 10
      grid_size: 640
      grid_size_eval: 128

    initial_condition:
      distribution: Normal
      parameters:
        mean: [0, 0, 0]
        std: [1, 1, 1]

    drift_pool: C:\\Users\\cesar\\Desktop\\Projects\\FoundationModels\\fimodemix\\data\\state_sde_full\\expressions_3d\\dimension_1\\3d-odeformer-no-inv-pool-filtered.csv
    diffusion_pool: C:\\Users\\cesar\\Desktop\\Projects\\FoundationModels\\fimodemix\\data\\state_sde_full\\expressions_3d\\dimension_1\\3d-odeformer-no-inv-pool-filtered.csv